apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-jenkins-minikube.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "k8s-jenkins-minikube.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "k8s-jenkins-minikube.fullname" . }}
    spec:
      containers:
        - name: {{ include "k8s-jenkins-minikube.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}